# Programa Ingenias+ Data Science

## Objetivo del proyecto

Predecir si una persona tendra un IMC anormal o no, en base a sus habitos y/o condiciones socioeconomicas

## Objetivo del notebook

Este notebook tiene como objetivo probar diferentes algoritmos de clasificacion para determinar cual puede brindarnos mejores parametros


## Importacion archivos y librerias

In [21]:
# imports de librerias y funciones
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from utils.codificaciones import *
from utils.funcions import *

In [22]:
# importo mi csv
friesgo = pd.read_csv('datasets/friesgo.csv')

# Preprocesado

Codificando las variables categoricas y eliminando los nan

In [23]:
# Aqui eliminaremos los registro que tengan nulos en la variable objetivo, comenzando por reemplazar lo valores 99 : ns/nc
friesgo['mantiene_ha_alta'] = friesgo['mantiene_ha_alta'].replace(99, np.nan)
friesgo.mantiene_ha_alta.unique()

array([ 2.,  1., nan])

In [24]:
# Primero busco cuales columnas efectivamente son categoricas y cuales numericas
variables_categoricas = ['cod_provincia','tamanio_aglomerado','sexo','condicion_actividad','ansiedad_depresion'
                           ,'nivel_actividad_fisica','condicion_fumador','consumo_sal'
                           ,'colesterol_elevado','freq_cons_alc','es_diabetico']
variables_numericas = ['edad','media_fv_diaria','imc_numerico']

In [25]:
# Creo una bd codificada a pesar de que ya esten codificados (para probar si algo cambia)
friesgo_cod = friesgo.copy()
le = LabelEncoder()
for columnas in variables_categoricas:
    friesgo_cod[columnas] = le.fit_transform(friesgo_cod[columnas])

In [26]:
friesgo_cod.mantiene_ha_alta.unique()

array([ 2.,  1., nan])

In [27]:
reemplazos={1:True,2:False}
friesgo_cod['mantiene_ha_alta'] = friesgo_cod['mantiene_ha_alta'].replace(reemplazos)

In [28]:
friesgo_cod.mantiene_ha_alta.unique()

array([False, True, nan], dtype=object)

In [29]:
calcular_nulos_y_porcentaje(friesgo_cod)

Nulos Porcentaje
id                          0       0.0%
cod_provincia               0       0.0%
tamanio_aglomerado          0       0.0%
sexo                        0       0.0%
edad                        0       0.0%
condicion_actividad         0       0.0%
ansiedad_depresion          0       0.0%
nivel_actividad_fisica      0       0.0%
condicion_fumador           0       0.0%
mantiene_ha_alta         2235      7.65%
consumo_sal                 0       0.0%
media_fv_diaria           753      2.58%
colesterol_elevado          0       0.0%
freq_cons_alc               0       0.0%
es_diabetico                0       0.0%
imc_numerico              705      2.41%

In [30]:
friesgo_cod = friesgo_cod.dropna()

In [31]:
calcular_nulos_y_porcentaje(friesgo_cod)

Nulos Porcentaje
id                          0       0.0%
cod_provincia               0       0.0%
tamanio_aglomerado          0       0.0%
sexo                        0       0.0%
edad                        0       0.0%
condicion_actividad         0       0.0%
ansiedad_depresion          0       0.0%
nivel_actividad_fisica      0       0.0%
condicion_fumador           0       0.0%
mantiene_ha_alta            0       0.0%
consumo_sal                 0       0.0%
media_fv_diaria             0       0.0%
colesterol_elevado          0       0.0%
freq_cons_alc               0       0.0%
es_diabetico                0       0.0%
imc_numerico                0       0.0%

In [32]:
friesgo_cod.shape

(25742, 16)

**Por ultimo, se realiza la division del modelo en train-test**

In [33]:
# Division del dataset en train-test en este caso el tamaño de la muestra sera del 30%
y = friesgo_cod['mantiene_ha_alta']
X = friesgo_cod.drop(columns=['mantiene_ha_alta'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Analisis modelos

## Modelo 1: Random Forest

## Modelo 2

## Modelo 3